content_repository/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required
from .views import KnowledgeBaseTemplateView, FileResourceListView, FileResourceCreateView, \
    FileResourceDetailView, FileResourceUpdateView, FileResourceDownloadView, \
    FileResourcePreviousVersionListView, FileResourcePreviousVersionDetailView, \
    FileResourcePreviousVersionDownloadView, FileResourceDeleteView, FileResourcePreviousVersionDeleteView

urlpatterns = patterns('',
                       url(r'^$', login_required(KnowledgeBaseTemplateView.as_view()), name='knowledge_base'),
                       url(r'^resources/$', login_required(FileResourceListView.as_view()), name='file_resource_list'),
                       url(r'^resources/create/$', login_required(FileResourceCreateView.as_view()), name='file_resource_create'),
                       url(r'^resources/update/(?P<pk>\d+)/$', login_required(FileResourceUpdateView.as_view()), name='file_resource_update'),
                       url(r'^resources/download/(?P<pk>\d+)/$', login_required(FileResourceDownloadView.as_view()), name='file_resource_download'),
                       url(r'^resources/(?P<pk>\d+)/$', login_required(FileResourceDetailView.as_view()), name='file_resource_detail'),
                       url(r'^resources/(?P<pk>\d+)/delete/$', login_required(FileResourceDeleteView.as_view()), name='file_resource_delete'),

                       # previous versions
                       url(r'^resources/(?P<current_version_pk>\d+)/previous/$', login_required(FileResourcePreviousVersionListView.as_view()), name='file_resource_previous_version_list'),
                       url(r'^resources/(?P<current_version_pk>\d+)/previous/(?P<pk>\d+)/$', login_required(FileResourcePreviousVersionDetailView.as_view()), name='file_resource_previous_version_detail'),
                       url(r'^resources/(?P<current_version_pk>\d+)/previous/(?P<pk>\d+)/download/$', login_required(FileResourcePreviousVersionDownloadView.as_view()), name='file_resource_previous_version_download'),
                       url(r'^resources/(?P<current_version_pk>\d+)/previous/(?P<pk>\d+)/delete/$', login_required(FileResourcePreviousVersionDeleteView.as_view()), name='file_resource_previous_version_delete'),
                       )

content_repository/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from rulez import registry
from django.core.exceptions import ObjectDoesNotExist
from users.models import Staff, CommitteeMember, send_notification_email


class KnowledgeBaseCategory(models.Model):
    """
    Categories that Resources are placed into
    """

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Knowledge Base Categories"

    def __unicode__(self):
        return "%s" % self.name


class KnowledgeBaseTag(models.Model):
    """
    Tags that Resources are placed into
    """

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return "%s" % (self.name)

    @classmethod
    def get_or_create_tag(cls, tag_name):
        new_tag = None
        try:
            new_tag = KnowledgeBaseTag.objects.get(name__iexact=tag_name)
        except ObjectDoesNotExist:
            new_tag = KnowledgeBaseTag.objects.create(name=tag_name)
        return new_tag


class FileResource(models.Model):
    """
    This class is to hold a reference to a file resource that
    was uploaded, and some associated attributes.
    """

    class Meta:
        verbose_name_plural = "Knowledge Base"

    file = models.FileField(upload_to="restricted/file_resources/")
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    author = models.ForeignKey(User)
    date_uploaded = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(KnowledgeBaseCategory)
    tags = models.ManyToManyField(KnowledgeBaseTag)

    def __unicode__(self):
        return "%s" % self.title

    def get_absolute_url(self):
        return reverse('file_resource_detail', kwargs={'pk': self.pk})

    def can_edit(self, user_obj):
        if CommitteeMember.is_member(user_obj):
            return True
        elif Staff.is_member(user_obj):
            return True
        elif user_obj == self.author:
            return True
        return False

    def can_view(self, user_obj):
        if CommitteeMember.is_member(user_obj):
            return True
        elif Staff.is_member(user_obj):
            return True
        return False

    def can_delete(self, user_obj):
        if self.fileresourcepreviousversion_set.all().exists():
            return False
        if CommitteeMember.is_member(user_obj):
            return True
        elif Staff.is_member(user_obj):
            return True
        return False

    def can_download_resource(self, user_obj):
        if CommitteeMember.is_member(user_obj):
            return True
        elif Staff.is_member(user_obj):
            return True
        return False

    def can_view_list(self, user_obj):
        if CommitteeMember.is_member(user_obj):
            return True
        elif Staff.is_member(user_obj):
            return True
        return False

    def send_file_update_email(self, request):
        com_members = CommitteeMember.objects.filter(send_notification_emails=True,
                                                     active=True).values_list('user__pk', flat=True)
        address_list = User.objects.filter(pk__in=com_members).values_list('email', flat=True)
        send_notification_email(self, address_list, request, subject="NCORE File Resource Updated")

registry.register('can_edit', FileResource)
registry.register('can_view', FileResource)
registry.register('can_delete', FileResource)
registry.register('can_view_list', FileResource)
registry.register('can_download_resource', FileResource)


class FileResourcePreviousVersion(models.Model):
    """
    This class is to hold a reference to a file resource that
    was previously uploaded
    """

    class Meta:
        verbose_name_plural = "Knowledge Base Previous Versions"

    file = models.FileField(upload_to="restricted/file_resources/")
    author = models.ForeignKey(User)
    date_uploaded = models.DateTimeField(null=True)
    current_version = models.ForeignKey(FileResource)

    def __unicode__(self):
        return "%s" % self.current_version.title

    def get_absolute_url(self):
        return reverse('file_resource_previous_version_detail', kwargs={'current_version_pk': self.current_version.pk,
                                                                        'pk': self.pk})

    def can_edit(self, user_obj):
        if Staff.is_member(user_obj):
            return True
        return False

    def can_view(self, user_obj):
        if CommitteeMember.is_member(user_obj):
            return True
        elif Staff.is_member(user_obj):
            return True
        return False

    def can_delete(self, user_obj):
        if CommitteeMember.is_member(user_obj):
            return True
        elif Staff.is_member(user_obj):
            return True
        return False

    def can_download_resource(self, user_obj):
        if CommitteeMember.is_member(user_obj):
            return True
        elif Staff.is_member(user_obj):
            return True
        return False

    def can_view_list(self, user_obj):
        if CommitteeMember.is_member(user_obj):
            return True
        elif Staff.is_member(user_obj):
            return True
        return False

registry.register('can_edit', FileResourcePreviousVersion)
registry.register('can_view', FileResourcePreviousVersion)
registry.register('can_delete', FileResourcePreviousVersion)
registry.register('can_view_list', FileResourcePreviousVersion)
registry.register('can_download_resource', FileResourcePreviousVersion)

content_repository/templates/_file_resource.html
{% load url from future %}
{% load knowledge_base_tags %}
<dl>
    <dt>Title</dt><dd><a target="_blank" href="{% url 'file_resource_download' pk=fileresource.pk %}">{{ fileresource.title }}</a></dd>
    <dt>Description</dt><dd>{{ fileresource.description }}</dd>
    <dt>Author</dt><dd>{{ fileresource.author.get_full_name }}</dd>
    <dt>Last Updated</dt><dd>{{ fileresource.date_uploaded }}</dd>
    <dt>Category</dt><dd>{{ fileresource.category }}</dd>
    <dt>Tags</dt><dd>{% for tag in fileresource.tags.all %}{{ tag }}{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</dd>
</dl>
{% if fileresource|can_edit_resource:user %}
    <p><a href="{% url 'file_resource_update' pk=fileresource.pk %}">Update this resource</a></p>
{% endif %}
{% if fileresource|can_delete_resource:user %}
    <p><a href="{% url 'file_resource_delete' pk=fileresource.pk %}">Delete this resource</a></p>
{% endif %}
{% if fileresource.fileresourcepreviousversion_set.all %}
    <p><a href="{% url 'file_resource_previous_version_list' current_version_pk=fileresource.pk %}">Previous Versions of This Resource</a></p>
{% endif %}

content_repository/templates/_file_resource_previous_version.html
{% load url from future %}
{% load knowledge_base_tags %}
<dl>
    <dt>Title</dt><dd><a target="_blank" href="{% url 'file_resource_previous_version_download' current_version_pk=object.current_version.pk pk=object.pk %}">{{ object.current_version.title }}</a></dd>
    <dt>Description</dt><dd>{{ object.current_version.description }}</dd>
    <dt>Author</dt><dd>{{ object.author.get_full_name }}</dd>
    <dt>Last Updated</dt><dd>{{ object.date_uploaded }}</dd>
    <dt>Category</dt><dd>{{ object.current_version.category }}</dd>
    <dt>Tags</dt><dd>{% for tag in object.current_version.tags.all %}{{ tag }}{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</dd>
</dl>

content_repository/templates/file_resource.html
{% extends "base.html" %}
{% load url from future %}
{% block breadcrumb %}<a href="/en/">Home</a>&raquo; <a href="{% url 'file_resource_list' %}">Repository</a> &raquo; Resource Detail{% endblock %}
{% block content %}
    <div class="nav-collapse collapse submenu">
        <h2>File Resource</h2>
        {% comment %}
        <ul class="nav nav-tabs ">
            <li {% if resource_upload_view %}class="active"{% endif %}><a href="{% url 'file_resource_create' %}"> Upload a Resource</a></li>
            <li {% if resource_list_view %}class="active"{% endif %}><a href="{% url 'file_resource_list' %}"> View Resources</a></li>
        </ul>
        {% endcomment %}
    </div>

    <div id="subbody">
    {% if form %}
        <form enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            <div class="help-block">{{ form.non_field_errors }}</div>
            <ul>
                {% for field in form %}
                    <label><strong>{{ field.label }}</strong></label>
                    {{ field }}<div class="help-inline">{{ field.errors }}</div>
                    <div class="dummydivider"></div>
                {% endfor %}
                <input type="submit" class="btn btn-primary"/>
            </ul>
        </form>
    {% else %}
        {% include "_file_resource.html" %}
    {% endif %}
    </div>
{% endblock %}

content_repository/templates/file_resource_list.html
{% extends "base.html" %}
{% load url from future %}
{% block extrahead %}
{# extra style stuff that Pam should remove #}
    <style type="text/css">
    ul{
        list-style-type: none;
        padding-left: 0px;
    }
    .pagination-centered{
        text-align: center;
    }
    .pagination-centered li{
        display: inline;
    }
    h4.reply_count{
        display: inline;
    }
    </style>
{% endblock %}
{% block breadcrumb %}<a href="/en/">Home</a>&raquo; Repository{% endblock %}
{% block content %}
    <div class="nav-collapse collapse submenu">
        <h2>File Resources</h2>
        <ul class="nav nav-tabs ">
            <li {% if resource_upload_view %}class="active"{% endif %}><a href="{% url 'file_resource_create' %}"> Upload a Resource</a></li>
            <li {% if resource_list_view %}class="active"{% endif %}><a href="{% url 'file_resource_list' %}"> View Resources</a></li>
        </ul>
    </div>
    
    <div id="subbody">
        {% if fileresource_list %}
            <form method="GET" action=".">
            <strong>Filter by category</strong>
            {% for field in category_form %}
                {{ field }}
            {% endfor %}
            <button type="submit" class="btn">Filter</button>
            <a href="{% url 'file_resource_list' %}" class="btn">View all</a>
        </form>
            <table class="table table-striped table-bordered">
                <thead>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Last Modified</th>
                    <th>Category</th>
                </thead>
                <tbody>
                    {% for fr in fileresource_list %}
                        <tr>
                            <td><a href="{{ fr.get_absolute_url }}">{{ fr.title }}</a></td>
                            <td>{{ fr.author.get_full_name }}</td>
                            <td>{{ fr.date_uploaded }}</td>
                            <td><a href="{% url 'file_resource_list' %}?category={{ fr.category.pk }}">{{ fr.category }}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include "_pagination_links.html" %}
        {% else %}
            <p>No File Resources in System</p>
        {% endif %}
    </div>
{% endblock %}

content_repository/templates/file_resource_previous_version.html
{% extends "base.html" %}
{% load url from future %}
{% block breadcrumb %}<a href="/en/">Home</a>&raquo; <a href="{% url 'file_resource_list' %}">Repository</a>
    &raquo; <a href="{{ object.current_version.get_absolute_url }}">File Resource Detail</a> &raquo; Previous Version{% endblock %}
{% block content %}
    <div class="nav-collapse collapse submenu">
        <h2>File Resource</h2>
        {% comment %}
        <ul class="nav nav-tabs ">
            <li {% if resource_upload_view %}class="active"{% endif %}><a href="{% url 'file_resource_create' %}"> Upload a Resource</a></li>
            <li {% if resource_list_view %}class="active"{% endif %}><a href="{% url 'file_resource_list' %}"> View Resources</a></li>
        </ul>
        {% endcomment %}
    </div>

    <div id="subbody">
    {% if form %}
        <form enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            <div class="help-block">{{ form.non_field_errors }}</div>
            <ul>
                {% for field in form %}
                    <label><strong>{{ field.label }}</strong></label>
                    {{ field }}<div class="help-inline">{{ field.errors }}</div>
                    <div class="dummydivider"></div>
                {% endfor %}
                <input type="submit" class="btn btn-primary"/>
            </ul>
        </form>
    {% else %}
        {% include "_file_resource_previous_version.html" %}
    {% endif %}
    </div>
{% endblock %}

content_repository/templates/file_resource_previous_version_list.html
{% extends "base.html" %}
{% load url from future %}
{% block extrahead %}
{# extra style stuff that Pam should remove #}
    <style type="text/css">
    ul{
        list-style-type: none;
        padding-left: 0px;
    }
    .pagination-centered{
        text-align: center;
    }
    .pagination-centered li{
        display: inline;
    }
    h4.reply_count{
        display: inline;
    }
    </style>
{% endblock %}
{% block breadcrumb %}<a href="/en/">Home</a>&raquo; <a href="{% url 'file_resource_list' %}">Repository</a>
    &raquo; <a href="{{ current_version.get_absolute_url }}">Resource Detail</a> &raquo; Previous Versions{% endblock %}
{% block content %}
    <div class="nav-collapse collapse submenu">
        {% comment %}
        <h2>File Resources</h2>
        <ul class="nav nav-tabs ">
            <li {% if resource_upload_view %}class="active"{% endif %}><a href="{% url 'file_resource_create' %}"> Upload a Resource</a></li>
            <li {% if resource_list_view %}class="active"{% endif %}><a href="{% url 'file_resource_list' %}"> View Resources</a></li>
        </ul>
        {% endcomment %}
    </div>
    
    <div id="subbody">
        {% if object_list %}
            <table class="table table-striped table-bordered">
                <thead>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Last Modified</th>
                    <th>Download Link</th>
                    <th>Delete</th>
                </thead>
                <tbody>
                    {% for fr in object_list %}
                        <tr>
                            <td><a href="{{ fr.get_absolute_url }}">{{ fr.current_version.title }}</a></td>
                            <td>{{ fr.author.get_full_name }}</td>
                            <td>{{ fr.date_uploaded }}</td>
                            <td><a href="{% url 'file_resource_previous_version_download' current_version_pk=fr.current_version.pk pk=fr.pk %}">Download</a></td>
                            <td><a href="{% url 'file_resource_previous_version_delete' current_version_pk=fr.current_version.pk pk=fr.pk %}">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include "_pagination_links.html" %}
        {% else %}
            <p>No Previous Versions in System. <a href="{{ current_version.get_absolute_url }}">Click here to view the current version</a></p>
        {% endif %}
    </div>
{% endblock %}

content_repository/templates/knowledge_base.html
{% extends "base.html" %}
{% load url from future %}
{% block breadcrumb %}<a href="/en/">Home</a>&raquo; Repository{% endblock %}
{% block content %}
    <h2 class="bump">Repository</h2>
    <ul>
        <li><a href="{% url 'file_resource_list' %}">Existing Resources</a></li>
        <li><a href="{% url 'file_resource_create' %}">Create a New Resource</a></li>
    </ul>
{% endblock %}

content_repository/templates/repository_confirm_delete.html
{% extends "base.html" %}
{% load url from future %}
{% block breadcrumb %}<a href="/en/">Home</a>&raquo; <a href="{% url 'file_resource_list' %}">Repository</a> &raquo; Resource Detail{% endblock %}
{% block content %}
    <div class="nav-collapse collapse submenu">
        <h2>Delete File Resource</h2>
    </div>

    <div id="subbody">
        <form enctype="multipart/form-data" action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete {{ object }}?</p>
            <p><input type="submit" value="Delete" class="btn btn-primary"/></p>
        </form>
    </div>
{% endblock %}